#!/bin/bash
# Daniel Melo
# this thing updates from remove repository, adds modifications to stage,
# commits it and pushes it to the remote again. Such commands!

txtbld=$(tput bold);
txtrst=$(tput sgr0);
reset=${txtrst};

echo "$txtbld> Updating sources...$reset";
git pull origin master;

echo "$txtbld> Adding all the modifications zed master did $reset";
git add --all;


printf "$txtbld> Gibe commit message plox! \t>>\t\t $reset";
echo "";
read message;

printf "\n\n$txtbld>Commiting changes... $reset";
git commit -m "{$message}";

printf "\n\n$red Updating changes to remote origin -> master $reset"
git push origin master;

printf "\n\n$txtbld Me did it! Me are good shell script, master! Gibe moar CPU! $reset";
echo "";